name: CD technoservs

on:
    push:
        branches:
            - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@master
        - name: Copy repo into azure Vm
          uses: appleboy/scp-action@master
          with:
            source: "."
            target: /home/sulli/Backend
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PRIVATEKEY }}
