name: CI
on:
  pull_request:
    branches: [develop, master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.x'

      - name: test_pull_request
        run: go test ../../Backend/Backend/.
